using HealthCTX.Domain.Attributes;

namespace HealthCTX.Domain.Encounters;

[FhirResource("Encounter")]
[FhirProperty("identifier", typeof(IEncounterIdentifier), Cardinality.Multiple)]
[FhirProperty("status", typeof(IEncounterStatus), Cardinality.Mandatory)]
[FhirProperty("statusHistory", typeof(IEncounterStatusHistory), Cardinality.Multiple, ToVersion: FhirVersion.R4)]
[FhirProperty("class", typeof(IEncounterClassCoding), Cardinality.Multiple, ToVersion: FhirVersion.R4)]
[FhirProperty("class", typeof(IEncounterClass), Cardinality.Multiple, FromVersion: FhirVersion.R5)]
[FhirProperty("classHistory", typeof(IEncounterClassHistory), Cardinality.Multiple, ToVersion: FhirVersion.R4)]
[FhirProperty("priority", typeof(IEncounterPriority), Cardinality.Optional)]
[FhirProperty("type", typeof(IEncounterType), Cardinality.Multiple)]
[FhirProperty("serviceType", typeof(IEncounterServiceTypeConcept), Cardinality.Optional, ToVersion: FhirVersion.R4)]
[FhirProperty("serviceType", typeof(IEncounterServiceType), Cardinality.Multiple, FromVersion: FhirVersion.R5)]
[FhirProperty("subject", typeof(IEncounterSubject), Cardinality.Optional)]
[FhirProperty("subjectStatus", typeof(IEncounterSubjectStatus), Cardinality.Optional, FromVersion: FhirVersion.R5)]
[FhirProperty("episodeOfCare", typeof(IEncounterEpisodeOfCare), Cardinality.Multiple)]
[FhirProperty("basedOn", typeof(IEncounterBasedOn), Cardinality.Multiple)]
[FhirProperty("careTeam", typeof(IEncounterCareTeam), Cardinality.Multiple, FromVersion: FhirVersion.R5)]
[FhirProperty("partOf", typeof(IEncounterPartOf), Cardinality.Optional)]
[FhirProperty("serviceProvider", typeof(IEncounterServiceProvider), Cardinality.Optional)]
[FhirProperty("participant", typeof(IEncounterParticipant), Cardinality.Multiple)]
[FhirProperty("appointment", typeof(IEncounterAppointment), Cardinality.Multiple)]
[FhirProperty("virtualService", typeof(IEncounterVirtualService), Cardinality.Multiple, FromVersion: FhirVersion.R5)]
[FhirProperty("period", typeof(IEncounterPeriod), Cardinality.Optional, ToVersion: FhirVersion.R4)]
[FhirProperty("actualPeriod", typeof(IEncounterActualPeriod), Cardinality.Optional, FromVersion: FhirVersion.R5)]
[FhirProperty("plannedStartDate", typeof(IEncounterPlannedStartDate), Cardinality.Optional, FromVersion: FhirVersion.R5)]
[FhirProperty("plannedEndDate", typeof(IEncounterPlannedEndDate), Cardinality.Optional, FromVersion: FhirVersion.R5)]
[FhirProperty("length", typeof(IEncounterLength), Cardinality.Optional)]
[FhirProperty("reasonCode", typeof(IEncounterReasonCode), Cardinality.Multiple, ToVersion: FhirVersion.R4)]
[FhirProperty("reasonReference", typeof(IEncounterReasonReference), Cardinality.Multiple, ToVersion: FhirVersion.R4)]
[FhirProperty("reason", typeof(IEncounterReason), Cardinality.Multiple, FromVersion: FhirVersion.R5)]
[FhirProperty("diagnosis", typeof(IEncounterDiagnosis), Cardinality.Multiple)]
[FhirProperty("account", typeof(IEncounterAccount), Cardinality.Multiple)]
[FhirProperty("dietPreference", typeof(IEncounterDietPreference), Cardinality.Multiple, FromVersion: FhirVersion.R5)]
[FhirProperty("specialArrangement", typeof(IEncounterSpecialArrangement), Cardinality.Multiple, FromVersion: FhirVersion.R5)]
[FhirProperty("specialCourtesy", typeof(IEncounterSpecialCourtesy), Cardinality.Multiple, FromVersion: FhirVersion.R5)]
[FhirProperty("hospitalization", typeof(IEncounterHospitalization), Cardinality.Optional, ToVersion: FhirVersion.R4)]
[FhirProperty("admission", typeof(IEncounterAdmission), Cardinality.Optional, FromVersion: FhirVersion.R5)]
[FhirProperty("location", typeof(IEncounterLocation), Cardinality.Multiple)]
public interface IEncounter : IResource;
